from enum import IntEnum

FRAME_BUFFER_SIZE = 128000
STREAM_LOG_INTERVAL = 30 # seconds

class StreamFormat(IntEnum):
    MEDIA_CODEC_UNKNOWN = 0x00
    MEDIA_CODEC_VIDEO_MPEG4 = 0x4C
    MEDIA_CODEC_VIDEO_H263 = 0x4D
    MEDIA_CODEC_VIDEO_H264 = 0x4E
    MEDIA_CODEC_VIDEO_MJPEG = 0x4F
    MEDIA_CODEC_AUDIO_AAC = 0x88
    MEDIA_CODEC_AUDIO_G711U = 0x89
    MEDIA_CODEC_AUDIO_G711A = 0x8A
    MEDIA_CODEC_AUDIO_ADPCM = 0X8B
    MEDIA_CODEC_AUDIO_PCM = 0x8C
    MEDIA_CODEC_AUDIO_SPEEX = 0x8D
    MEDIA_CODEC_AUDIO_MP3 = 0x8E
    MEDIA_CODEC_AUDIO_G726 = 0x8F


class IOTCSessionMode(IntEnum):
    P2P = 0
    RLY = 1
    LAN = 2
